margin = 92
indent = 4
remove_extra_newlines = false
always_use_return = false
short_to_long_function_def = false
always_for_in = false
import_to_using = false
pipe_to_function_call = false
whitespace_ops_in_indices = false
whitespace_in_kwargs = false
whitespace_typedefs = false
annotate_untyped_fields_with_any = false
format_docstrings  = false
conditional_to_if = true
normalize_line_endings = "unix"
align_assignment = true
align_struct_field = true
align_pair_arrow = true
align_matrix = true
trailing_comma = "nothing"
