# Assets
#
# `InjectAssets` runs before Documenter's `RenderDocument` step, so that the
# assets are in place before the HTML pages are written. `WriteHoverData` runs
# after it, when the rendered bibliography entries are available.

"""Pipeline step to automatically insert the bundled assets.

The assets shipped with the package are copied into
`build/assets/documentercitations/` and registered in the `assets` list of the
[`Documenter.HTML`](@extref Documenter.HTMLWriter.HTML) format, so that
`Documenter` emits the corresponding `<link>` and `<script>` tags in the
`<head>` of every page. Thus, no manual `assets` entry is required in
[`Documenter.makedocs`](@extref). These are the `citations.css` stylesheet
(unless the [`CitationBibliography`](@ref) plugin was instantiated with
`insert_css=false`) and the stylesheet and script for the [Citation hover
popups](@ref) (unless `show_hover=false`). The two options are independent of
each other.

Stylesheets are inserted *before* any user-defined assets, so that custom CSS
still takes precedence over the bundled ones, see [CSS Styling](@ref).

The step is skipped if the documentation has no HTML output format. If any of
the user-defined assets is an unmodified copy of a `citations.css` that was
bundled with some version of `DocumenterCitations`, the step issues a warning.
"""
abstract type InjectAssets <: Builder.DocumentPipeline end

Selectors.order(::Type{InjectAssets}) = 5.5  # Before RenderDocument

function Selectors.runner(::Type{InjectAssets}, doc::Documenter.Document)
    Documenter.is_doctest_only(doc, "InjectAssets") && return
    inject_assets!(doc)
end


# The folder containing the assets shipped as part of the package
const ASSETS_FOLDER = normpath(joinpath(@__DIR__, "..", "assets"))

# The names of the assets to insert, relative to `ASSETS_FOLDER`
const ASSETS = ("citations.css",)

# The name of the data file generated by `WriteHoverData`
const HOVER_DATA_FILENAME = "citations-data.js"

# The sub-folder of `build/assets` into which the assets are copied
const ASSETS_SUBFOLDER = "documentercitations"

# The URI of an asset in the build folder, relative to the root of the site
_asset_uri(filename) = "assets/$ASSETS_SUBFOLDER/$filename"


# Copy the bundled assets into the build folder and register them with the HTML
# format object
function inject_assets!(doc::Documenter.Document)
    bib = Documenter.getplugin(doc, CitationBibliography)
    (bib.insert_css || bib.show_hover) || return  # nothing to inject
    html = _find_html_format(doc.user.format)
    isnothing(html) && return  # no HTML output
    destination = joinpath(doc.user.build, "assets", ASSETS_SUBFOLDER)
    mkpath(destination)
    if bib.insert_css
        _warn_stale_css(doc, html)  # must run *before* registering our own asset
        for filename in ASSETS
            # Insert before any user-defined assets, so that custom CSS wins
            _insert_asset!(html, filename, destination; prepend=true)
        end
    end
    if bib.show_hover
        _insert_asset!(html, "citations-hover.css", destination; prepend=true)
        # The data file is written only after rendering, by `WriteHoverData`.
        # Documenter emits the `<script>` tag for a registered local asset
        # without checking that the file exists, so it can be registered
        # already here. It must come before the script that reads it.
        _register_asset!(html, _asset_uri(HOVER_DATA_FILENAME))
        _insert_asset!(html, "citations-hover.js", destination)
    end
    return
end


# Copy a bundled asset into the build folder and register it with the HTML
# format object
function _insert_asset!(html, filename, destination; prepend=false)
    cp(joinpath(ASSETS_FOLDER, filename), joinpath(destination, filename); force=true)
    _register_asset!(html, _asset_uri(filename); prepend=prepend)
    return
end


# Register `uri` as a local asset of the HTML format, unless already present.
# With `prepend=true`, the asset is inserted before any user-defined assets
# (so that custom user CSS takes precedence over bundled stylesheets).
function _register_asset!(html::Documenter.HTML, uri::AbstractString; prepend::Bool=false)
    _has_asset(html.assets, uri) && return
    asset = Documenter.asset(uri; islocal=true)
    if asset isa eltype(html.assets)
        if prepend
            pushfirst!(html.assets, asset)
        else
            push!(html.assets, asset)
        end
    else
        # Can happen if the `assets` of `Documenter.HTML` were given as a
        # vector that cannot hold an `HTMLAsset`, e.g., a vector of
        # `RawHTMLHeadContent` only
        @warn "InjectAssets: cannot register $(repr(uri)). Add `assets=String[$(repr(uri))]` to `Documenter.HTML` manually."
    end
    return
end


# Find the `Documenter.HTML` format object in the (possibly multiple) output
# formats of the documentation, or `nothing` if there is no HTML output
_find_html_format(format::Documenter.HTML) = format

_find_html_format(::Any) = nothing

function _find_html_format(formats::AbstractVector)
    for format in formats
        html = _find_html_format(format)
        isnothing(html) || return html
    end
    return nothing
end


# Check whether `uri` is already registered in the `assets` of the HTML format
function _has_asset(assets, uri)
    return any(assets) do asset
        asset isa Documenter.HTMLWriter.HTMLAsset && asset.uri == uri
    end
end


# Normalize a stylesheet before hashing: line endings, trailing whitespace on
# each line, and surrounding blank lines do not affect whether a file is a
# verbatim copy of a bundled version
function _normalize_css(str::AbstractString)
    lines = rstrip.(split(str, r"\r\n|\r|\n"))  # handles all three line endings
    return String(strip(join(lines, "\n")))
end


_css_hash(str::AbstractString) = bytes2hex(sha256(_normalize_css(str)))


# The `_css_hash` of every version of `citations.css` that this package has
# ever shipped or recommended, newest first.
#
# When editing `assets/citations.css`, PREPEND the hash of the new content here
# and KEEP all existing entries: they are what allows `_warn_stale_css` to
# recognize an outdated copy in a user's `docs/src/assets` folder. The test in
# `test/test_assets.jl` fails if the first entry does not match the current
# `assets/citations.css`.
const KNOWN_CSS_HASHES = (
    "ad197a59c8c6e614024dd464d9b9693a0ab5bb8479bcb2c1d423fb30ff7ee87b",  # since v1.3.3
    "f2986976ab24cbac4d387e85c0c87c297591d0a153160913ee4bf01551402763",  # v1.0 – v1.3.2
    "a84156754fe3efcce021d9be813b2d3fa4e1cd83ef5669e9aac013c44b543b74",  # before v1.0
)


# Warn about entries in the `assets` of the HTML format that are unmodified
# copies of a bundled `citations.css`: they are redundant, and they would
# silently override any future update of the bundled stylesheet
function _warn_stale_css(doc::Documenter.Document, html::Documenter.HTML)
    for asset in html.assets
        asset isa Documenter.HTMLWriter.HTMLAsset || continue
        (asset.islocal && (asset.class == :css)) || continue
        # Skip our own asset, which is still registered in `html.assets` if the
        # same `Documenter.HTML` object is reused for a second `makedocs` run
        startswith(asset.uri, "assets/$ASSETS_SUBFOLDER/") && continue
        file = joinpath(doc.user.root, doc.user.source, asset.uri)
        isfile(file) || continue
        if _css_hash(read(file, String)) in KNOWN_CSS_HASHES
            @warn "The `assets` of `Documenter.HTML` contain $(repr(asset.uri)), which is an unmodified copy of the `citations.css` bundled with DocumenterCitations. As of v1.5, the stylesheet is inserted automatically by default, so both the `assets` entry and the file itself can be deleted. Keeping the copy may mask any future update of the bundled stylesheet. To suppress the bundled stylesheet instead, use `CitationBibliography(bibfile; insert_css=false)`."
        end
    end
    return
end


"""Pipeline step to write the data file for the [Citation hover popups](@ref).

After `Documenter` has rendered the HTML pages, this step writes a
`citations-data.js` file into `build/assets/documentercitations/`. It maps the
anchor name of each entry in a canonical `@bibliography` block to the rendered
HTML of that entry (collected during rendering) and the path of the page
containing the block. The bundled `citations-hover.js` script, registered by
[`InjectAssets`](@ref), uses this data to construct the popups.

The step is skipped if the documentation has no HTML output format, or if the
[`CitationBibliography`](@ref) plugin was instantiated with
`show_hover=false`.
"""
abstract type WriteHoverData <: Builder.DocumentPipeline end

Selectors.order(::Type{WriteHoverData}) = 6.5  # After RenderDocument

function Selectors.runner(::Type{WriteHoverData}, doc::Documenter.Document)
    Documenter.is_doctest_only(doc, "WriteHoverData") && return
    write_hover_data(doc)
end


# Write the `citations-data.js` file mapping anchor names to entry data.
#
# The entries are shipped in this separate script instead of being embedded in
# the pages (e.g., as hidden elements that the popups could be cloned from):
# markup that is hidden by CSS or the `hidden` attribute would still show up in
# text-mode browsers, which would then have a copy of the full bibliography
# scattered over every page that has citations.
function write_hover_data(doc::Documenter.Document)
    bib = Documenter.getplugin(doc, CitationBibliography)
    bib.show_hover || return
    html = _find_html_format(doc.user.format)
    isnothing(html) && return  # no HTML output
    data = Dict(
        anchor_key => Dict("html" => entry_html, "page" => page) for
        (anchor_key, (entry_html, page)) in bib.hover_entries
    )
    json = Documenter.JSDependencies.json_jsescape(data)
    # Escaping `</` guards against `</script>` appearing in the entry HTML
    json = replace(json, "</" => "<\\/")
    destination = joinpath(doc.user.build, "assets", ASSETS_SUBFOLDER)
    mkpath(destination)
    file = joinpath(destination, HOVER_DATA_FILENAME)
    header = "// Generated by DocumenterCitations: bibliography entry data for citation hover popups."
    write(file, "$header\nwindow.DocumenterCitationsHoverData = $json;\n")
    return
end
